### PR TITLE
Analytical_oM: Add IResultSeries interface

### LINKED ISSUE #1378: Analytical_oM: Add IResultSeries interface
#### Description:

Addition of interface for results storing a list of doubles as values in contrast to the IResultItem type results storing results as single value double per result.

Added in support of result types that require a more efficient data storage compared to the IResultItem type result at the cost of a more complex data structure

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #1378

### CODE REVIEW

**Review by enarhi — APPROVED** [review]
LGTM, reviewed with a couple tests cases and implementation looks fit for purpose.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
I have reviewed the code and do not see any major issues. Functionality review from @enarhi is still valid as last commit was compliance only.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 6109072212

**Pull request merged**
