### PR TITLE
Architecture_oM: IElement0D implemented by BuildersWork.Opening

### LINKED ISSUE #1257: Implement IElementxD interface by Architecture.BuildersWork.Opening
#### Description:

First of all conceptually, it is a spatial object, then more practically, this will be needed for e.g. transformations etc.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1257

### Test files

See https://github.com/BHoM/BHoM_Engine/pull/2572

### Additional comments

I was considering between different numbers of dimensions to be applied, but finally I came to a conclusion that the closest concept is 0D since the location of the opening is represented by `Cartesian`, ergo its position in space is a point. Happy to hear others' opinion! @rolyhudson @al-fisher @tiagogrossi @kayleighhoude @michaelhoehn

### CODE REVIEW

**Comment by al-fisher** [comment]
The be honest - the XD interface you want to add to the object will depend on the engine methods you need/want to support in the first instance. And long term you may want more than one.

`Element0D` makes sense immediately - interacting with the cartesian location as you say.
Longer term perhaps `Element2D` could be useful for laundry like snapping and tiding up of openings? This would then require being similar to the `IOpening` so more work down the line.
But certainly agree with principle of start with the simple and add future functionality as needed.

**Comment by pawelbaran** [comment]
I think this one is ready for review, in combination with https://github.com/BHoM/BHoM_Engine/pull/2572.

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance

**Comment by pawelbaran** [comment]
@FraserGreenroyd similar to (or even more funky than) https://github.com/BHoM/BHoM_Engine/pull/2572: how can implementation of an interface in the oM increase the number of null failures?

**Comment by FraserGreenroyd** [comment]
> @FraserGreenroyd similar to (or even more funky than) [BHoM/BHoM_Engine#2572](https://github.com/BHoM/BHoM_Engine/pull/2572): how can implementation of an interface in the oM increase the number of null failures?

It is linked across all the PRs sharing the branch name, so the work as a whole is introducing more null-failures than previously.

It could be that your Engine branch is behind and so the result of the check on the primary branch is better than your PR, which is classed as a failure, so it's worth checking your Engine branch is up to date, and that then every method you're adding/modifying is handling nulls appropriately.

**Review by FraserGreenroyd — APPROVED** [review]
This PR is fine. Will now review Engine PR and check suitable methods have been implemented.

**Comment by pawelbaran** [comment]
@BHoMBot check null-handling

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
