### PR TITLE
Verification_oM: compliance fixed

### LINKED ISSUE #1652: Verification_oM: incompliant constructor parameter name on RequirementResult
#### Broken rules:

Constructor input names must match property names, 2nd input to `RequirementResult` constructor breaks that rule.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1652

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by IsakNaslundBh — APPROVED** [review]
Happy to approve and good to merge as long as compliance and serialisation are both passing

**Comment by IsakNaslundBh** [comment]
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
