### PR TITLE
LifeCycleAssesment_oM: Add IResultItem to EnvironmentalMetricResult

### LINKED ISSUE #1446: LifeCycleAssessment_oM: EnvironmentalMetricResult should implement IResultItem
#### Description:

https://github.com/BHoM/BHoM/pull/1379 made `IObjectResult` no longer implement `IResultItem`. In the PR, the EnvironmentalMetricResult was not given this interface explicitly.

To be added.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #1446 

Simply adding IResultItem interface to EnvironmentalMetricResult, which was implicit from IObjectResult before https://github.com/BHoM/BHoM/pull/1379

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
The interface has been added which meets the issue described and makes the interface implementation explicit as desired. Happy to merge to alpha.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation
@BHoMBot check null-handling

**Review by michaelhoehn — APPROVED** [review]
Happy to merge this.

**Comment by michaelhoehn** [comment]
going for merge after https://github.com/BHoM/LifeCycleAssessment_Toolkit/pull/288 and all dependent PRs are taken care of.

**Comment by michaelhoehn** [comment]
@BHoMBot check core

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Still happy given only an interface being added

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
