### PR TITLE
New DisplayText attribute

### LINKED ISSUE #1440: Provide a centralised solution for setting a display text on enum values
#### Description:
Currently enum values are shown as they are defined in the code. For example, Central Europe will show as `CentralEurope` since we cannot have spaces in an enum name. 

To solve that, I have been using the `Description` attribute to store a UI friendly text representation along with my own methods to convert enums to and from text. As the number of cases for this solution grows, it would be better to switch to a centralised solution.

It is however important to not that, within the BHoM, the `Description` attribute has already been used on enums to provide actual descriptions and cannot therefore be used to contain the display text. 

image

I suggest to use a new attribute: `DisplayTextAttribute` that will serve that single purpose. The `ParseEnum` method in the engine will need to be updated to support that new attribute. We will also need to update teh ToText method so it now looks for the `DisplayText` attribute on enum values.

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #1440 

See issue for description.

### Test files
See Engine PR: https://github.com/BHoM/BHoM_Engine/pull/2930

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by FraserGreenroyd — APPROVED** [review]
See [this review](https://github.com/BHoM/BHoM_Engine/pull/2930#pullrequestreview-1149405802)

**Comment by adecler** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Comment by travispotterBH** [comment]
@adecler Can you please add this to the wiki on attributes describing its use?

**Comment by adecler** [comment]
@travispotterBH , Done.

**Pull request merged**
