### PR TITLE
Update Assembly Version

### LINKED ISSUE #1125: Update AssemblyFileVersion
The `AssemblyFileVersion` attribute should now be updated to read `4.1.0.0` for all `AssemblyInfo.cs` files within this repository for the 4.1 milestone.

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #1125

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed from a CI/CD perspective.

**Review by michaelhoehn — APPROVED** [review]
LGTM

**Review by IsakNaslundBh — APPROVED** [review]
LGTM

**Pull request merged**
