### PR TITLE
Data_oM: Create LibrarySettings

### LINKED ISSUE #1300: Data_oM: Add settings object in support of custom library paths.
#### Description:

Required to solve https://github.com/BHoM/BHoM_Engine/issues/1153

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #1300 

### Test files

See Engine PR for testfiles

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core

**Comment by IsakNaslundBh** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Review by pawelbaran — APPROVED** [review]
This is OK if the Engine is OK 👍

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
