### PR TITLE
Environment_oM: Add opening configuration object

### LINKED ISSUE #1210: Environment_oM: Opening Design Options
Following the work done by @linaeriksson on the SAP prototype workflows, it would be good to move the `OpeningOption` object from SAP_oM to Environment_oM, with a suitable method in the Environment_Engine to allow model building from geometry for Environment workflows to be handled easier.

Object definition is as per current definition on SAP_oM.

Object name should be `OpeningDesignOption`.

FYI: @charliebrookerBH @rboulton-BH @michaelhoehn @BingWangUS

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #1210 

### Test files
[Available here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Environment_oM/%231213-OpeningConfigurations/OpeningConfigurations.gh?csf=1&web=1&e=IUp0Gv)

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix copyright headers ref. 2026717358

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Review by michaelhoehn — APPROVED** [review]
LGTM!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
