### PR TITLE
BHoM: Documentation Link updates

### LINKED ISSUE #1570: Documentation URL No Longer Valid Post Directory Reorganization
https://github.com/BHoM/BHoM/blob/a4c48079558ce4d29ce32a28f22236fd83d2eeb6/Structure_oM/Elements/Bar.cs#L41

One such example. Worthwhile to do a review for all: 
https://github.com/search?q=repo%3ABHoM%2FBHoM%20https%3A%2F%2Fbhom.xyz%2Fdocumentation&type=code

https://github.com/search?q=org%3ABHoM%20https%3A%2F%2Fbhom.xyz%2Fdocumentation&type=code

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #1570

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Review by michaelhoehn — APPROVED** [review]
Looks good. Links all work as expected.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
