### PR TITLE
Humans_oM: Avalue analysis improvements

### PR DESCRIPTION
**Pull request by rolyhudson**
### Issues addressed by this PR

Closes https://github.com/BHoM/BHoM_Engine/issues/2442

### Test files

[Test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Humans_Engine/%232449-AValueAnalysisImprovements/A_valueexplorer.gh?csf=1&web=1&e=nNW1zS)

### CODE REVIEW

**Comment by rolyhudson** [comment]
@BHoMBot check code-compliance

**Comment by rolyhudson** [comment]
@BHoMBot check documentation-compliance

**Comment by rolyhudson** [comment]
@BHoMBot check copyright-compliance

**Comment by rolyhudson** [comment]
@BHoMBot check project-compliance

**Comment by rolyhudson** [comment]
@BHoMBot check versioning

**Review by jdarcyBHE — APPROVED** [review]
Test file run and components working as expected

**Comment by rolyhudson** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2694566668

**Comment by rolyhudson** [comment]
@BHoMBot check required

**Comment by rolyhudson** [comment]
@FraserGreenroyd request for null-handling dispensation:
as far as I can see all the null-handling errors are from outside the scope of this PR. If any relate directly to files changed in this PR I am happy to deal with them.

**Review by michaelhoehn — APPROVED** [review]
I've reviewed the code and performed a functionality review. I appreciate the descriptions added within this scope. However, I will be following this up with another issue to add better descriptions generally for things that have already been merged (AValue query method). 

I also agree with your thoughts to create a couple of datasets regarding things like head shape and any other programmable profiles.

**Comment by rolyhudson** [comment]
@BHoMBot check required

**Comment by rolyhudson** [comment]
@BHoMBot check required

**Review by michaelhoehn — APPROVED** [review]
All LGTM!

**Comment by michaelhoehn** [comment]
@BHoMBot check copyright-compliance

**Comment by michaelhoehn** [comment]
@BHoMBot ready-to-merge

**Comment by michaelhoehn** [comment]
@BHoMBot check ready-to-merge

**Comment by rolyhudson** [comment]
Closing this to re open PR on branch from updated master

**Pull request closed without merging**
