### PR TITLE
Graphics_oM: Result display improvements

### LINKED ISSUE #1366: Graphics_oM: Add step gradient object
#### Description:

Current [Gradient](https://github.com/BHoM/BHoM/blob/main/Graphics_oM/Colours/Gradient.cs ) class is used for finding interpolated values between colours. For some display use cases it is required to have a class of similar structure that instead gives the same colour for a specific range of the gradient, e.g. red for all values between 0 and 1, green for all values between 2 and 3 and purple for all values higher than 3 etc.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #1366

- Adding SteppedGradient in support of visualisation methods in Results_Engine.
- Adding some basic interfaces in structure namespace for results containing the same properties.

### CODE REVIEW

**Review by alelom — DISMISSED** [review]

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check code-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Review by alelom — APPROVED** [review]

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
