### PR TITLE
Environment_oM: Update descriptions

### LINKED ISSUE #710: Environment_oM: documentation of panels and openings and materials
As per title, better descriptions for panels and openings and material fragments is needed.

### PR DESCRIPTION
**Pull request by rboulton-BH**
### Issues addressed by this PR

Closes #710 

Update descriptions to Environment objects

### Test files

N/A

### Changelog

 - Update descriptions within Building object
 - Removed FrameFactorValue from Opening object

### Additional comments

- As discussed, proposal to remove FrameFactorValue to avoid conflict with calculated value based on "Edges" & "InnerEdges" geometry.

### CODE REVIEW

**Comment by al-fisher** [comment]
Hi @kayleighhoude @michaelhoehn - capturing our conversation on the Sprint Kick Off call just now.
- @michaelhoehn to reach out and plan pushing forward of Environment_oM Descriptions. 🙏 
- All to update progress and plannings on this PR here.
- Plan is to all commit directly to this PR - so please do coordinate and plan with namespaces you guys are working on to not overlap and then feel free to commit and comment frequently and freely 👍 😸 

I have just updated the public wiki page on code attributes to capture the latest guidence.
[reminder here](https://github.com/BHoM/documentation/wiki/Code-Attributes#description-authoring-guidelines-%EF%B8%8F)

Awesome stuff! Thanks guys!
FYI @FraserGreenroyd @rboulton-BH @vbeardow @JAbboudBH

**Comment by al-fisher** [comment]
@michaelhoehn see updated comment above RE starting new PR. 
Once new draft is raised can reference here and safely close this and delete branch. Thanks

**Comment by michaelhoehn** [comment]
@al-fisher per discussion, closing this PR. For those looking to remain involved in this effort, please refer to the new PR #751.

FYI @rboulton-BH @kayleighhoude  @FraserGreenroyd @cskinnerBH @kentonphillips

**Comment by al-fisher** [comment]
Thanks @michaelhoehn

**Pull request closed without merging**
