### PR TITLE
Structure_oM: Remove Embodied Carbon from MaterialFragments

### LINKED ISSUE #1070: Structure_oM: Remove EmbodiedCarbon property from MaterialFragments
#### Description:

The rationale is that having these additional properties could add confusion when evaluating embodied carbon using the LCA_Toolkit. Additionally, to keep these numbers, additional documentation regarding the source and calculation methods would be required at a minimum to justify the overall figure being used. 

From the following MaterialFragments: 
- [x] Aluminium
- [x] Concrete
- [x] GenericIsotropicMaterial
- [x] GenericOrthotropicMaterial
- [x] IMaterialFragment
- [x] Steel

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #1070 

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Structure_oM/Issue1070-RemoveEmbodiedCarbonFromMaterialFragments?csf=1&web=1&e=A2B66W

### Changelog

- Removed `EmbodiedCarbon` attribute from `MaterialFragments` to avoid overlap and conflicts with the work being done in the LCA_Toolkit

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check installer

**Comment by peterjamesnugent** [comment]
@BHoMBot check installer

**Comment by peterjamesnugent** [comment]
@BHoMBot check compliance

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

**Pull request merged**
