### PR TITLE
Update Assembly Information

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Update Assembly Information to include description

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by michaelhoehn** [comment]
@BHoMBot check project-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance
@BHoMBot check versioning
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Review by alelom — APPROVED** [review]

**Pull request merged**
