### PR TITLE
BHoM - Issue 42 - Physical Objects

### LINKED ISSUE #42: Create Physical Wall, Floor and Ceiling BHoM Objects
### This issue has been archived 

Historic issue archive can be found [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive)

### PR DESCRIPTION
**Pull request by ZiolkowskiJakub**
### Issues addressed by this PR
Implementing 2D Physical Objects such as Wall, Floor and Roof

Closes #42

### CODE REVIEW

**Comment by rwemay** [comment]
This looks good to me. Suggest @IsakNaslundBh review/approve if that's ok. I assume nothing to test on this one, unless it's being done in parallel with a Revit_Toolkit branch that matches changes.

**Comment by al-fisher** [comment]
Agree - looks good - thanks @ZiolkowskiJakub!

> CompoundLayer should be in Properties folder and namespace

👍 yes!

> IObject2D to an interface folder

Also 👍 yes!

Although - IObject2D might not want to leave in Architecture long term?!
Think this looks good for now though - with a possible revision of names/namespaces after prototyping complete. Would propose merging following the above tweaks!

Really great to get this all in place. 😄

**Comment by ZiolkowskiJakub** [comment]
Hi @al-fisher,

Code has been reorganised. I also moved IObject2D and its properties (Object2DProperties) to Common namespace to fully reflect your comments. I hope this is okay.

**Comment by al-fisher** [comment]
Thanks @ZiolkowskiJakub happy to proceed with this.
I am offline (sort of 😄 !!) so if @IsakNaslundBh @rwemay happy to approve let’s merge. Good progress forward.

Then as an aside perhaps for next steps beyond this PR next week - been considering and wonder if the logical class/interface structure will be to merge IObject2D and IElement2D (and their counter parts) to work for both purposes.
With then empty interfaces IAnalytical and IPhysical in order to tag and filter.
As discussed a good diagram to show class structure for all base and geometric objects and interfaces across the 3 dimensions will now help in order to bottom out fully and plan relationships 
@pawelbaran @adecler  FYI

**Comment by rwemay** [comment]
Thanks @al-fisher . @IsakNaslundBh if you can review/approve, I'm happy to merge this avo.

**Comment by IsakNaslundBh** [comment]
I have made some tweaks:

- Updated some usings to make code compile after reshuffle of files
- Adding Copyright header to all the added files
- Adding commenting lines and header
- Removed all commented out code to be put in the engine, and raised issues for it:
   - https://github.com/BHoM/BHoM_Engine/issues/838
   - https://github.com/BHoM/BHoM_Engine/issues/839
   - https://github.com/BHoM/BHoM_Engine/issues/840
   - https://github.com/BHoM/BHoM_Engine/issues/841

**Comment by al-fisher** [comment]
Looks good - @IsakNaslundBh for completeness - can you please reconfirm happy as I have pushed some minor commits that have dismissed your stale review.
Minor typos and tidying of sub-folders.

**Comment by pawelbaran** [comment]
Good to see this happening - adding the physical objects to panels will be a great improvement allowing to resolve a few dirty workarounds I implemented in the Revit_Toolkit.

I like the idea of `IAnalytical` and `IPhysical`!

**Pull request merged**
