### PR TITLE
Structure_oM: Turn Load<T> into IELementLoad<T>

### LINKED ISSUE #946: Structure_oM: Turn Load<T> into IElementLoad<T>
#### Broken rules:

Load<T> is an abstract class. This does not comply with general BHoM regulations for BHoMObjects

#### Suggestions to restore compliance:

Turn the abstract class into an interface, `IElementLoad<T>` with the same properties.
Need to make sure all toolkits gets aligned with this change.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #946 

Changing the abstract class `Load<T>` into an interface.
Renaming to `IElementLoad<T>` to better highlight intent
As no longer an abstract class but an interface, all properties have been added to all implementing classes and an direct inheritance to BHoMObejct added.

### Test files

Test file testing that the Type component upgrades correctly and that all existing load classes still de-serialise correctly. Please note, for the Type component to upgrade properly, the Versioning_Toolkit needs to be built after this PR.

https://burohappold.sharepoint.com/:f:/s/BHoM/EgYptE6GOE9Hs_xqcghkGWwB7EHdw6KHumPfR6ufZJcleQ?e=B1Lfsv

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
Fewer toolkits than expected needed update. Only three, all updated and PRs raised.

**Comment by peterjamesnugent** [comment]
@IsakNaslundBh I think you need to Update from /master for this PR - I was unable to build the BHoM_Engine otherwise. The CI does not appear to be complaining.

**Review by peterjamesnugent — APPROVED** [review]
Versioning works well, all loads serialise correctly.

**Pull request merged**
