### PR TITLE
Environment_oM: Modify Space Object and Ventilation

### LINKED ISSUE #882: Environment_oM: Modify Space Object
#### Description:
Modify environment space object to include new properties:
Acoustics
OccupantDensity
Exhaust
FireProtection
Edit the Infiltration Gain property to just be Infiltration
Edit the Space Type to take in a string rather than an enum (to give flexibility)
image

### PR DESCRIPTION
**Pull request by kayleighhoude**
Modify Space Object and Ventilation

### NOTE: Depends on 
https://github.com/BHoM/BHoM_Engine/issues/1791

   
### Issues addressed by this PR

Closes #882

### Test files
image

### CODE REVIEW

**Comment by kayleighhoude** [comment]
FYI @rboulton-BH @JAbboudBH @michaelhoehn adjustments to the space object per our discussions

**Comment by FraserGreenroyd** [comment]
@al-fisher @adecler this is ready for merging with green checks :smile:

There is a dependent PR:
https://github.com/BHoM/BHoM_Engine/pull/1792

Thanks! :smile:

**Pull request merged**
