### PR TITLE
Update Assembly Version

### LINKED ISSUE #1226: Update AssemblyFileVersion
The `AssemblyFileVersion` attribute should now be updated to read `4.2.0.0` for all `AssemblyInfo.cs` files within this repository for the 4.2 milestone.

### PR DESCRIPTION
**Pull request by BHoMBot**
Closes #1226

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by FraserGreenroyd — APPROVED** [review]
Reviewed from a CI/CD perspective. Will let discipline merge when happy.

**Review by adecler — APPROVED** [review]
LGTM

**Comment by adecler** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2241583582

**Comment by FraserGreenroyd** [comment]
@adecler I'm not waiting for the Azure one to finish - if you want to merge before I come back to this feel free :smile:

**Pull request merged**
