### PR TITLE
Facade_oM: Added IElementM to FrameEdge

### LINKED ISSUE #1204: Facade_oM: Make FrameEdge IElementM
#### Description:
As per title

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #1204

### CODE REVIEW

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Review by michaelhoehn — APPROVED** [review]
LGTM

**Comment by enarhi** [comment]
@BHoMBot check-ready-merge

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Comment by enarhi** [comment]
@BHoMBot check installer

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
