### PR TITLE
8.0 Deployment

### PR DESCRIPTION
**Pull request by BHoMBot**
#### Feature
 - [Extract Story Drifts](https://github.com/BHoM/BHoM/pull/1639)
   -  Added `StoreyDrift` Class to structural results;
 - [Geometry_oM: Changes for refactor of polyline offset](https://github.com/BHoM/BHoM/pull/1632)
 - [Verification_oM added](https://github.com/BHoM/BHoM/pull/1644)
#### Compliance
 - [Start of milestone changes for 8.0](https://github.com/BHoM/BHoM/pull/1638)
 - [Verification_oM: SpecificationResult made immutable](https://github.com/BHoM/BHoM/pull/1648)

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check serialisation -force

**Review by chrismcoulter — APPROVED** [review]
oM_Lighting passed testing 13DEC24

**Review by peterjamesnugent — APPROVED** [review]
Confirm StoreyDrifts are included in installers, and beta installer test scripts are working as intended. Happy to approve from a structures perspective.

**Review by pawelbaran — APPROVED** [review]
Happy to approve from the side of Verification

**Review by vgreen-BH — APPROVED** [review]
Facade_oM passed using 12/17/2024 install

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
