### PR TITLE
Architecture_oM: Add ceiling tile object

### LINKED ISSUE #1029: Architecture_oM: Add ceiling tile object
To facilitate with https://github.com/BHoM/BHoM_Engine/issues/2049 we want a `CeilingTile` object. This will also help with the removal/renaming of CustomData as Revit_TK stores the ceiling pattern as a custom data parameter.

It would be good if the Ceiling Tile object can be made up of Edges (implementing IEdge from Analytical oM) so as to match other types of handling this. Maybe the Ceiling Tile can then be an IPanel? @IsakNaslundBh what do you think on that?

Alternatively, just a simple polyline defining its geometry is enough for now.

Then the Ceiling object can have a property that includes a collection of the `CeilingTile` objects which the Revit TK can then be updated to use instead of CustomData.

### PR DESCRIPTION
**Pull request by JohannaOlin1**
### Issues addressed by this PR
Closes #1029 

Facilitating BHoM/BHoM_Engine#2049 by creating a ceiling tile object.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
Have asked @IsakNaslundBh to check this doesn't conflict with him before merging happens :smile:

**Review by michaelhoehn — APPROVED** [review]
LGTM

**Comment by adecler** [comment]
@FraserGreenroyd , was there any versioning provided separately to cover this change ?

**Comment by FraserGreenroyd** [comment]
@adecler just to capture our chat from the call earlier for public record - no versioning was provided for this change as it was only a property addition :smile:

**Pull request merged**
