### PR TITLE
Update Assembly Version

### PR DESCRIPTION
**Pull request by BHoMBot**
Update Assembly Version to 5.0.0.0
Update Assembly File Version to 5.0.0.0

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Approved from DevOps, will leave merge to toolkit lead or will merge automatically on 29th September 2021.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3731753811

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

**Pull request merged**
