### PR TITLE
Base_oM: Adding missing virtual keyword on Enumeration properties

### LINKED ISSUE #1324: Base_oM: add the virtual keyword on Enumeration properties
#### Broken rules:
All properties should be virtual and they are not on the Enumeration object

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #1324

See issue

### Test files
No need

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHomBot check required

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 4259969786

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
