### PR TITLE
Analytical_oM: Elevate Graph objects from Elements sub folder to own primary folder

### LINKED ISSUE #1261: Analytical_oM: move the "Graph" folder out of "Elements" to the root level.
#### Broken rules:

Move the "Graph" folder out of "Elements" to the root level. This will make its meaning equivalent to the "Elements" folder.

#### Suggestions to restore compliance:

See above.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #1261

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Review by Tom-Kingstone — APPROVED** [review]
On code review: the changes made follow the original issue as set out, and seeing as the bot likes the versioning, I'm happy to approve this.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
