### PR TITLE
Data_Engine: Add generic graph query methods

### LINKED ISSUE #787: Need for enum to determine if a GraphNode neighbours are incoming, outgoing or both.
Need an enum to determine `GraphNode` neighbours required for example in querying `Engine.Neighbours` which current only returns outgoing only.

### PR DESCRIPTION
**Pull request by rolyhudson**
Add an enum to determine `GraphNode` neighbours required for example in `Engine.Neighbours`

### Issues addressed by this PR
Closes #787

### CODE REVIEW

**Comment by rolyhudson** [comment]
Yes agreed @adecler `GraphNodeNeighbours` is not informative either changing for more meaningful `GraphLinkDirection` (using `GraphLink` to align with BHoM link naming).

**Comment by FraserGreenroyd** [comment]
This PR also needs a suitable `feature` `bug` `documentation` or `compliance` label for change log purposes please :smile:

**Comment by adecler** [comment]
@FraserGreenroyd , Done (and more)

**Pull request merged**
