### PR TITLE
Programming_oM: Remove dependency to GetShallowClone

### LINKED ISSUE #1027: Programming_oM: Remove dependency to GetShallowClone
#### Broken rules:
Following https://github.com/BHoM/admin/issues/9, the `GetShallowClone` method will soon be removed. 
So the `BlockNode` and `LoopNode` constructor should not rely on it. If cloning is required, the code should be moved to a `Engine.Create` method so it can call the `Engine.ShallowClone` methods.

Note that those constructors are also non compliant since the input names are not matching the property names.

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #1027

See issue for details

### CODE REVIEW

**Review by alelom — DISMISSED** [review]
Works fine, LGTM.

**Comment by adecler** [comment]
I had to do a rebase of the branch for CI to be happy, @alelom do you mind reapproving ?

**Review by alelom — APPROVED** [review]

**Pull request merged**
