### PR TITLE
Graphics_oM: add ColourFragment

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes https://github.com/BHoM/BHoM/issues/1048

### CODE REVIEW

**Review by adecler — APPROVED** [review]
LGTM in isolation. Would be good to have someone actually using this also review.

**Comment by FraserGreenroyd** [comment]
@alelom can you advise an additional reviewer per @adecler comments or if you're happy this code is not yet in wide circulation to impact users? :smile:

**Comment by alelom** [comment]
> @alelom can you advise an additional reviewer per @adecler comments or if you're happy this code is not yet in wide circulation to impact users? 😄

This code is used only on a minor case in Speckle/3Drepo toolkit. Not widespread so safe to merge like this.

**Review by FraserGreenroyd — APPROVED** [review]
Happy from my perspective

**Pull request merged**
