### PR TITLE
Geometry_oM: Adding IElement2D interface to the PlanarSurface

### LINKED ISSUE #426: Geometry_oM: Add IElement2D to ICurve and PlanarSurface
the IElement2D interface could be added to PlanarSurface, but to be able to extract internal openings, the same will be needed for ICurve.

Not doing this as part of https://github.com/BHoM/BHoM/issues/424 as needs to be verified as correct strategy.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #426

Making PlanarSurface implement IElement2D

### Test files

See engine PR

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check null-handling

**Review by alelom — APPROVED** [review]
Approved based on test scripts and after discussion on https://github.com/BHoM/BHoM_Engine/pull/2835

**Pull request merged**
