### PR TITLE
Base_oM: Add Description To IFragment

### LINKED ISSUE #1277: BHoM: Add a Description to IFragment interface
#### What is missing/incorrect?

We currently do not have a description onto the Fragment interface. In light of the recent chat, we should be clear onto the usage of Fragments by adding a description, to avoid further confusion in the future.

A tentative one:

```cs

[Description("Indicates objects that can exist independently or be attached to other BHoM objects as part of their `FragmentSet` property.")]
```

@al-fisher @pawelbaran @IsakNaslundBh @adecler @FraserGreenroyd do we like it?

### PR DESCRIPTION
**Pull request by al-fisher**
### Issues addressed by this PR

Closes #1277 

Adding a description as discussed and proposed in issue.

### CODE REVIEW

**Review by jamesramsden-bh — APPROVED** [review]
Description looks fine :)

**Review by FraserGreenroyd — APPROVED** [review]
Have reviewed following the hack session and this description meets the issue and describes the `IFragment` appropriately - happy to deploy.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
