### PR TITLE
Diffing_oM: Rename Id to ID as appropriate

### LINKED ISSUE #1107: Diffing_oM: renaming of "Id" terms to "ID"
#### Broken rules:

As title. This should extend to description attributes and all references in the Engine and elsewhere.

#### Suggestions to restore compliance:

As above.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes #1107

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 20422835378

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Review by Tom-Kingstone — APPROVED** [review]
Aligns with linked issue as set out, and happy to approve as all checks are passing. Also approving change from camel_case to pascalCase in the case of `_from` and `_to` to `From` and `To`.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
