### PR TITLE
Environment_oM: Revised Profile Object, Created ProfileDay, Revised ProfileType

### LINKED ISSUE #840: Environment_oM: Revise Profile Object and Profile Enums
#### Description:
Revise the current Profile object and Profile Enums that sit under the Environment_oM over a series of prototypes with @cskinnerBH and @rboulton-BH for applicability to software use cases as well as user workflows

### PR DESCRIPTION
**Pull request by kayleighhoude**
### Issues addressed by this PR

Closes #840 

### Test files

image

### Additional comments
To be tested in workflows by @cskinnerBH and @rboulton-BH

### CODE REVIEW

**Comment by michaelhoehn** [comment]
@cskinnerBH would be good to have your review and comment here if possible! 😃

**Comment by kayleighhoude** [comment]
@BingWangUS hoping this is in line with your thoughts here: https://github.com/BuroHappoldEngineering/Climate_Toolkit/issues/184#event-3317443231

**Comment by al-fisher** [comment]
Thanks @rboulton-BH - @FraserGreenroyd

**Pull request merged**
