### PR TITLE
LifeCycleAssessment_oM: EPD Refactor to extend functionality

### LINKED ISSUE #1209: LifeCycleAssessment_oM: EPD object refactor
#### Description:

Current EPD structures need to be refactored to allow for proper assessment of metrics and their associated properties. 

It is currently overly complicated to associate phases with metrics within element EPDs. Additionally, the creation of the EPD has lots of unnecessary data that should simply be within fragments. 

image

### PR DESCRIPTION
**Pull request by michaelhoehn**
### Issues addressed by this PR

Closes #1209 

- Objects have been heavily refactored to allow for multiple phases and environmental impact metrics.
- Objects now make use of fragments where needed (Density, AdditionalData, and Dimensionality for scaling purposes)
- Results have been better organised to reflect generic metric outputs to allow for more than GWP results. 

### Test files

[Test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/LifeCycleAssessment_oM/%231242-Refactor-EPD/EPD%20Refactor.gh?csf=1&web=1&e=78GOwz)
[Link to PR installer](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/LifeCycleAssessment_oM/%231242-Refactor-EPD/LifeCycleAssessment_oM-%231209-Refactor-EPD.msi?csf=1&web=1&e=QEyNIC)

### CODE REVIEW

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by michaelhoehn** [comment]
^Fresh rebase since it's been a while 😄

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Review by enarhi — APPROVED** [review]
LGTM

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Comment by michaelhoehn** [comment]
@FraserGreenroyd this PR and others associated are now ready to merge, barring of course BHoMBot checks. Also worth noting there was an erroneous merge on CQD toolkit that has since been reverted. I'm assuming CI checks will fail due to branch naming inconsistencies caused by reverting. Please let me know if you'd like to work through this together.

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Review by enarhi — APPROVED** [review]
LGTM

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Comment by michaelhoehn** [comment]
@FraserGreenroyd this is the situation I was referring to with the IImmuttable interface. I need `{ get; set; }` for LCA toolkit engine method functionality. The constructor was made to facilitate that, but compliance doesn't like it. Last time we worked on GlobalWarmingPotentialResult we came to the same impass.

**Comment by michaelhoehn** [comment]
@BHoMBot check core

**Comment by michaelhoehn** [comment]
@BHoMBot check versioning

**Comment by michaelhoehn** [comment]
@BHoMBot check versioning

**Comment by michaelhoehn** [comment]
@BHoMBot check versioning

**Comment by michaelhoehn** [comment]
@BHoMBot check core

**Comment by michaelhoehn** [comment]
@BHoMBot check installer

**Comment by michaelhoehn** [comment]
@BHoMBot check versioning

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2898810798

**Review by FraserGreenroyd — APPROVED** [review]
Functionality was tested by users via a PR artefact. Changes since have been for versioning, so these PRs are fit for merge with passing checks.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2898874410

**Pull request merged**
