### PR TITLE
Structure_oM: Add Auto Option to LoadPanelSupportConditions

### LINKED ISSUE #1196: Structure_oM: Add Auto to LoadPanelSupportConditions
#### Description:

Ability to assign `LoadPanelSupportConditions` as auto for Load Panels.

### PR DESCRIPTION
**Pull request by annastigenberg**
### Issues addressed by this PR

Closes #1196

### Test files

[Test File](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%2FStructure%5FoM%2F%231196%20%2D%20Add%20auto%20to%20LoadPanelSupportConditions%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%2FStructure%5FoM)

### CODE REVIEW

**Review by IsakNaslundBh — CHANGES_REQUESTED** [review]
Even though I agree that the auto option probably is best placed either alphabetically or on top, I think we might have to move it to the bottom right now for the reason of versioning.

In GH it looks like adding the option in reshuffles the dropdowns, which I fear could mess up some scripts or similar.

I put you testfile in a folder and added a versioning file there,

https://burohappold.sharepoint.com/:f:/s/BHoM/EqnBebHcwpZKhR5AHpGjUo4BSgSfQCy1mcEsLExgVOi-6A?e=Sik1AP

The rightmost panel is what the values were when I built the script on master:

image

Moving the new entry to the bottom makes all the others stay as they were.

@adecler is this a known issue? I have some vague memory of fixing this before, but might have been in like 2 UI versions ago...

@FraserGreenroyd fyi in case you need to update some enums.

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready to merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check serialisation

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
