### PR TITLE
Reflection_oM: Fix PreviousInput and Targets attributes serialisation

### LINKED ISSUE #1176: Reflection_oM: some attributes don't serialise correctly
#### Description:
More precisely `PreviousInputNamesAttribute` and `TargetsAttribute`

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #1176

Pretty straightforward. Those two types were `IImmutable` but didn't have the constructor that matches the properties.

### Test files
You can use the validation script for serialisation but, honestly, it is just faster to do this:

image

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by adecler** [comment]
@BHoMBot check copyright

**Comment by adecler** [comment]
@FraserGreenroyd , can we have a dispensation to allow attributes to have multiple constructors ? We will generally need two:
- one for the interface of the attribute itself (limited to a small set of types)
- one for the serialisation with BHoM

**Comment by adecler** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 1789576167

**Review by FraserGreenroyd — APPROVED** [review]
LGTM

**Pull request merged**
