### PR TITLE
Migrate ISettings to the oM.Base namespace

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

See https://github.com/BHoM/BHoM_UI/pull/394 for more details

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
This LGTM with versioning being happy with the change made in [this PR](https://github.com/BHoM/BHoM_UI/pull/394).

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation
@BHoMBot check project-compliance
@BHoMBot check documentation-compliance
@BHoMBot check core
@BHoMBot check copyright-compliance
@BHoMBot check code-compliance
@BHoMBot check installer

**Comment by adecler** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
