### PR TITLE
Reflection_oM: Improved name change support on method arguments

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 

Support https://github.com/BHoM/BHoM_UI/pull/330
   
### Issues addressed by this PR

Provides new attribute needed for https://github.com/BHoM/BHoM_UI/pull/330

### Test files
See https://github.com/BHoM/BHoM_UI/pull/330

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
I have run the test outlined on the UI and am happy this is working as desired.

**Review by pawelbaran — APPROVED** [review]
Tested, works as expected on changes made in https://github.com/BHoM/Revit_Toolkit/pull/891.

**Comment by adecler** [comment]
@BHoMBot check installer

**Comment by adecler** [comment]
@BHoMBot, I am not sure I believe you on that one: 

image

CheckInstaller usually takes around 10 minutes and allows us to access details straight away.

@FraserGreenroyd , FYI.

**Comment by FraserGreenroyd** [comment]
> **Edit:** My bad, this is me on morning brain. Didn't realise that we would now have to run a installer check on both BHoMBot and Azure separately (I assumed the main point was to not have to remember the azure command lines). Is that a long term thing or is it just a transition phase ?

To confirm for record as discussed in stand up, its a transition phase, once we're happy with how BHoMBot is performing, we will phase out required checks from Azure and turn them on from BHoMBot instead :smile: unfortunately until then Azure commands still have to be run manually for now 🛩️ 

Dunno why I picked the small airplane emoji - a smiley face didn't seem appropriate and it came up and looked cool, so I used it. 🚴

**Pull request merged**
