### PR TITLE
Physical_oM: Adding IElement and IPhysical interfaces to MeshElement

### LINKED ISSUE #1455: Shouldn't MeshElement implement any interfaces?
#### Description:

As in the title, today @adecler raised a question whether `MeshElement` should not implement any interfaces, particularly:
- `IPhysical`
- `IElementM`
- `IElement`

We also had a discussion around the name, which we both do not like too much, but we did not come up with anything better so will not raise it as a separate issue 🙈

### PR DESCRIPTION
**Pull request by adecler**
### Issues addressed by this PR

Closes #1455 

### Test files
Not required here. Just code inspection

### CODE REVIEW

**Review by michaelhoehn — APPROVED** [review]
Tested and approved. This element implements the correct interfaces based on the referenced issue.

**Review by FraserGreenroyd — APPROVED** [review]
Changes meet the issue and make sense following offline discussion with @adecler . Happy to deploy.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
