### PR TITLE
Ground_oM: Add initial commit for oM

### LINKED ISSUE #1548: Ground_oM: Add project for ground related objects
#### Description:

New oM required for objects related to ground investigations such as `Borehole`, `Geology` etc.

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #1548 

### Test files

CI/CD

### Changelog

- Added Ground_oM for future development planned in 6.4 milestone

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
If the bots happy then this is a reasonable addition in advance of objects coming in during draft PRs without merging prior to the 6.3 beta to avoid versioning issues as discussed offline with @peterjamesnugent

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
