### PR TITLE
Environment_oM: Update opening option to include opening type

### LINKED ISSUE #1217: Environment_oM: Opening Configuration Options don't include Opening Type
Pointed out by @rboulton-BH - woops!

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #1217 

### Test files
[Here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Environment_oM/%231218-OpeningTYpe?csf=1&web=1&e=XIhF7P)

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by michaelhoehn — APPROVED** [review]
LGTM

**Comment by michaelhoehn** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
