### PR TITLE
Diffing_oM: add required property to DiffingConfig to fix behaviour when custom ObjectDifference is needed

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes https://github.com/BHoM/BHoM/issues/1368

### Test files

See https://github.com/BHoM/Revit_Toolkit/issues/1168.

### CODE REVIEW

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Comment by alelom** [comment]
@BHoMBot check required

**Review by pawelbaran — APPROVED** [review]

**Comment by alelom** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref. 5551165223

**Pull request merged**
