### PR TITLE
Versioning_oM: Add oM from Versioning_Toolkit with VersioningEvent

### PR DESCRIPTION
**Pull request by adecler**
### NOTE: Depends on 

https://github.com/BHoM/Versioning_Toolkit/pull/159
  
### Issues addressed by this PR

This PR is done within the context of solving this issue: https://github.com/BHoM/BHoM_UI/issues/389

The reason for adding this project is to store the new VersioningEvent class that will be used to collect the list of all upgrades that occurred on BHoM objects and components.

### Test files
This can be tested within the context of the related PR in the BHoM Engine repo or with the related PR in the BHoM_UI.

### CODE REVIEW

**Comment by adecler** [comment]
@BHoMBot check required

**Comment by adecler** [comment]
@BHoMBot check copyright-compliance

**Comment by adecler** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
See the review on [this PR](https://github.com/BHoM/BHoM_UI/pull/390)

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
