### PR TITLE
Test_oM: Return Test_oM to BHoM

### LINKED ISSUE #1076: Test_oM: The return
Bring back Test_oM - following discussion [here](https://github.com/BHoM/BHoM/discussions/1061).

Migrate objects from Test_Toolkit that @IsakNaslundBh requires.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #1076 

### Additional comments
Code moved verbatim, no changes made other than copyright and compliance.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check documentation compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot fix project file ref. 1385150040

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check documentation compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Review by IsakNaslundBh — APPROVED** [review]
Looks good to me. Correct files migrated over.

**Comment by IsakNaslundBh** [comment]
Putting a do-not-merge tag on until Test_Toolkit has been ironed out

**Comment by FraserGreenroyd** [comment]
Test_Toolkit is [ready to go](https://github.com/BHoM/Test_Toolkit/pull/293#pullrequestreview-528462409) :smile:

**Pull request merged**
