### PR TITLE
Diffing_oM: added property in DiffConfig to control MaxDifferences

### LINKED ISSUE #836: Diffing_oM: Add control over max differences to DiffConfig
#### Description:

When simply wanting to check if an object is equal or not, and not caring to much about what is different, there is no need to go to deep into the object and keep on checking as soon as a difference in property has been found.

Would suggest adding some "MaxDifferences" property to the diffconfig to control this.

Would assume this to substantially speed up the above usecase, being able to set this to 1.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Adds the option to regulate MaxDifferences as in https://github.com/BHoM/BHoM_Engine/pull/1710

Closes #836

### CODE REVIEW

**Comment by alelom** [comment]
Sorry @IsakNaslundBh didn't realise there were still issues. Let's see if this makes compliance happy. Cheers

**Comment by IsakNaslundBh** [comment]
@alelom this has conflicts in it now. Will leave it up to you how to handle this.

**Comment by al-fisher** [comment]
Just popping a `no-not-merge` on this PR until after the beta release, as classed as not a `severity:critical` `bug`

**Comment by al-fisher** [comment]
PR lockdown for beta is now over - removing `no-not-merge`

**Comment by alelom** [comment]
> Still compliance issues and CheckCore is failing. Would consider remaking this PR as so small and has conflicts.

Replaced by https://github.com/BHoM/BHoM/pull/948

**Pull request closed without merging**
