### PR TITLE
Enivironment_oM: Replace reference to "Zone" in Dwelling.cs

### LINKED ISSUE #1315: Environment_oM: Replace reference to 'Dwelling' with 'Zone'
#### Description:

Current dwelling object is designed as a collector for a group of spaces. This functionality would be useful more broadly than just for a dwelling so should be generalised to 'Zone'.

### PR DESCRIPTION
**Pull request by emilsvedjer**
### Issues addressed by this PR

Closes #1315 

Replaced reference from "Dwelling" to "Zone"

### CODE REVIEW

**Comment by emilsvedjer** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by FraserGreenroyd — APPROVED** [review]
LGTM, matches the issue and discussions around the naming.

@rboulton-BH @milogillot-BH you'll want to update SAP Toolkit which won't happen as part of this process.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
