### PR TITLE
BHoM: Legacy attributes removed

### LINKED ISSUE #1544: BHoM: Legacy attributes could be deleted?
#### Description:
During today's session with @adecler we found out that the following attributes are not used anywhere:
- [`AbbreviationAttribute`](https://github.com/BHoM/BHoM/blob/develop/BHoM/Attributes/AbbreviationAttribute.cs)
- [`AssemblyUrlAttribute`](https://github.com/BHoM/BHoM/blob/develop/BHoM/Attributes/AssemblyUrlAttribute.cs)
- [`ReleasedAttribute`](https://github.com/BHoM/BHoM/blob/develop/BHoM/Attributes/ReleasedAttribute.cs)

I believe they could be removed, but happy to wait for the green light from the originator (@al-fisher).

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1544

### Test files

Passing installer check should be enough.

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning
@BHoMBot check installer

**Review by al-fisher — COMMENTED** [review]
Thanks @pawelbaran - see comment on issue here: https://github.com/BHoM/BHoM/issues/1544#issuecomment-1878948507

**Comment by pawelbaran** [comment]
Thanks @al-fisher, both ways work for me: either keeping the attribute or removal and reinstantiation when needed. Would be great if you could request changes if you prefer the former or approve if the latter is OK 👍

**Review by al-fisher — CHANGES_REQUESTED** [review]
Given the vote - I would say keep the `AbbreviationAttribute`
And raise a documentation issue to update https://bhom.xyz/documentation/BHoM_oM/Base_oM/Attributes/ to document appropriate usage. 
Happy for you to assign that new issue to me 😄

**Comment by pawelbaran** [comment]
`AbbreviationAttribute` brought back and https://github.com/BHoM/documentation/issues/95 raised @al-fisher 👍

**Review by al-fisher — APPROVED** [review]
Thanks @pawelbaran - appreciate that edit.
I will action that documentation issue to capture the past knowledge and intent. Cheers!

Approving based on code review and expectation of a happy installer check and CI

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Approving based on code review, changes match issue and discussion.

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: unit-tests

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am authorising dispensation to be granted on check ref: 20262368680

**Comment by FraserGreenroyd** [comment]
I have dispensated installer because it passed on BHoM_Engine and then got confused following the work @pawelbaran and I did this morning... hopefully all resolved now.

@BHoMBot check ready-to-merge

**Pull request merged**
