### PR TITLE
Data_oM: LogicalAnd and LogicalOr requests added

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

This PR is resolving #645 to some extent, but happy to keep the issue open as it would be good to make sure that `LogicalOrRequest` does not do exactly same thing as `BatchRequest`.

### CODE REVIEW

**Comment by pawelbaran** [comment]
@FraserGreenroyd `ILogicalRequests` will enable building logical queries. Let me explain this on an example: the user may want to pull e.g. only Revit elements of certain type that belong to a certain workset. Such user could:
a) pull all element of given type and then filter them by workset
b) use `LogicalAndRequest`

The advantage of the latter is that it does not require converting all objects, but only the ones of interest, additionally it makes things much easier for the end user. Looking into the original issue may also spot some light on the idea.

**Comment by adecler** [comment]
I am fine with this. 
Probably good to make sure you coordinate with @rwemay  as he is looking into very similar things at the moment.
Also worth pinging @emidio-piermarini for his early work on Mongo queries.

**Comment by pawelbaran** [comment]
@al-fisher @rwemay could we get the final blessing on this one from one of you and merge? Thanks!

**Pull request merged**
