### PR TITLE
Geometry_oM: Add support closed, planar, non self-intersecting curve types

### LINKED ISSUE #1392: Geometry_oM: Add support for enforced Closed, planar curve types
#### Description:

Spinning off of https://github.com/BHoM/BHoM_Engine/pull/2802 and https://github.com/BHoM/BHoM_Engine/issues/2797, the potential benefits from having a classification of curves that are Closed, Planar and Non-self intersection, to avoid the need to repeatedly call those methods came up as a way forward to add further clarity and performance gain to some of the more heavy lifting methods in the Geometry namespace.

The suggestion forward is to implement the changes highlighted in the following diagram:

image

where green are new interfaces to be added, blue new classes to be added and yellow classes to implement a new interface.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #1392

### Changelog

- Adding IBoundary interface for closed, planar, non self-intersecting curves
- Adding support for various types of curves fulfilling the requirements on the IBoundary interface.

### CODE REVIEW

**Review by alelom — APPROVED** [review]
Approved based on code review and test [as per my comment on the Engine PR](https://github.com/BHoM/BHoM_Engine/pull/2841#pullrequestreview-987813006). The two questions on the script there should ideally be answered prior to merging.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot please check compliance
@BHoMBot please check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
