### PR TITLE
Structure_oM: Update LinkConstraint descriptions to Primary/Secondary nomenclature

### LINKED ISSUE #1101: Structure_oM: Remove reference to master/slave in description of LinkConstriant
#### Broken rules:

Descriptions in LinkConstraint did not get updated in https://github.com/BHoM/BHoM/pull/961

#### Suggestions to restore compliance:

Update the descriptions

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #1101 

Alignes the descriptions with changes made in https://github.com/BHoM/BHoM/pull/961

### CODE REVIEW

**Review by al-fisher — DISMISSED** [review]
LGTM

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by peterjamesnugent** [comment]
@IsakNaslundBh there's one more instance that was not picked up in #961, likely because it is `MasterNode`:
https://github.com/BHoM/BHoM/blob/d5998b2c6681dcb6362a614b21ce1648af1970a9/Structure_oM/Elements/RigidLink.cs#L43

Can you add that to this PR please.

**Review by peterjamesnugent — CHANGES_REQUESTED** [review]
@IsakNaslundBh there's one more instance that was not picked up in #961, likely because it is `MasterNode`:
https://github.com/BHoM/BHoM/blob/d5998b2c6681dcb6362a614b21ce1648af1970a9/Structure_oM/Elements/RigidLink.cs#L43

Can you add that to this PR please.

**Comment by IsakNaslundBh** [comment]
Good catch @peterjamesnugent . Should have made a full search for master/slave. Have done that now, the only remaining reference in structure_oM is in the versioning now as far as I can see. Have pushed your requested change

**Review by peterjamesnugent — APPROVED** [review]
LGTM.

**Comment by al-fisher** [comment]
thanks @peterjamesnugent

**Pull request merged**
