### PR TITLE
BHoM: IPersistentAdapterId not to require set on PersistentId

### LINKED ISSUE #1266: BHoM: `IPersistentAdapterId` not to require `set` on `PersistentId`
There is no reason why `IPersistentAdapterId` should to require the `set` on `PersistentId`. This limits its implementation on Fragments that must be `IImmutable` (e.g. `RevitIdentifiers` @pawelbaran ).

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #1266

### CODE REVIEW

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance

**Review by pawelbaran — APPROVED** [review]
LGTM from the code perspective and all checks pass.

**Comment by pawelbaran** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
