### PR TITLE
Graphics_oM: Adding RenderCurve class

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

fixes part of #1271 

Adding RenderCurve class to display curve with line thickness.

### Test files

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Graphics_oM/Graphics_oM-%231271-AddRenderCurve?csf=1&web=1&e=Uvpn7O

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Review by al-fisher — APPROVED** [review]
Approving this as part of chain of PRs.
Tested alongside the application in Rhino/GH.

**Comment by al-fisher** [comment]
Happily approving this based on simple addition adding huge functionality benefit.
On reviewing I did however have some questions regarding which interfaces this new class should implement.

i.e. should we have 
``` C#
public class RenderCurve : IGeometry, IElement1D, IRender
```

See `RenderPoint` e.g.
Is a question for debate and equally issue already raised here for discussion about alternative approach for relationship between IRender and IGeometry objects 
https://github.com/BHoM/BHoM/issues/1275 

Happy to merge this specific PR and progress with utilising this functionality - but @IsakNaslundBh FYI good to keep track of above issue and agree long term strategy at some stage

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
