### PR TITLE
Update Assembly Version

### PR DESCRIPTION
**Pull request by BHoMBot**
Updates Assembly Version to 4.3

### CODE REVIEW

**Review by FraserGreenroyd — APPROVED** [review]
Approved from a CI/CD perspective.

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 3074771191

**Pull request merged**
