### PR TITLE
Reflection_oM: Update output to allow larger number of outputs

### LINKED ISSUE #891: Reflection_oM: Add Output<...> supporting larger number of outputs
#### Description:

Current limit is 5. A few methods will need larger number of outputs than the current limit. Should add up to 10.

### PR DESCRIPTION
**Pull request by rwemay**
### Issues addressed by this PR

Closes #891

### CODE REVIEW

**Comment by rwemay** [comment]
This is to facilitate a method that's returning 7 outputs but has scope to increase. @IsakNaslundBh  and I thought 10 as a practical limit.

**Comment by rwemay** [comment]
@IsakNaslundBh , I think may be better to go with my initial gut of a dictionary, although not just for 'other' but all objects output. What do you think?

**Comment by FraserGreenroyd** [comment]
> This is to facilitate a method that's returning 7 outputs but has scope to increase. @IsakNaslundBh and I thought 10 as a practical limit.

Ok that seems reasonable to me :smile:

**Comment by al-fisher** [comment]
> @IsakNaslundBh , I think may be better to go with my initial gut of a dictionary, although not just for 'other' but all objects output. What do you think?

Yeah - not ideal to have to make the choice of when to output dictionary or when to manage with multi-output. However 10 will also not be enough! We will always want more 😄 
So inclined to agree with a dictionary approach

**Comment by rwemay** [comment]
@FraserGreenroyd , I also thought about breaking into smaller parts, but for this particular method it does need a significant number of outputs as we're deriving things from a significant number of objects/relationships.

**Comment by adecler** [comment]
> However 10 will also not be enough! We will always want more

I am not sure I agree. There is a point where the outputs make more sense as a single bundle object (e.g. `IResult`). 

Also worth mentioning that methods requiring a larger number of outputs will be exponentially rarer. And we have only needed 5 outputs so far despite having thousands of methods. So not convinced we will ever reach more than 10 that cannot be logically bundled.

**Pull request merged**
