### PR TITLE
Facade_oM: ConstructionOffsetFragment

### LINKED ISSUE #1140: Facade_oM: Construction offset fragment
#### Description:

A fragment which defines offset distance from the center line of a facade construction type.

This would be useful to define the offset of a glazed opening from opaque construction during panel creation.

### PR DESCRIPTION
**Pull request by vgreen-BH**
### Issues addressed by this PR

Closes #1140 

Adding fragment to Facade_oM that defines offset distance. This can be applied to wall cross sections or glazing cross sections to offset them from the facade centerline.

### CODE REVIEW

**Review by enarhi — COMMENTED** [review]
Copyright needs updating and fragment should be removed from name. We also need to add a description to OffsetDistance. Other than that, looks good!

**Review by enarhi — APPROVED** [review]
LGTM!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 1683860729

**Comment by enarhi** [comment]
@BHoMBot I am authorising dispensation to be granted on check ref. 1683860729

**Comment by enarhi** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 1683860729

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 1683860729

**Pull request merged**
