### PR TITLE
BHoM: Fragments to be `IObject` instead of `IBHoMObject`

### LINKED ISSUE #563: Fragments to be IObject instead of IBHoMObject
#### Broken rules:
See discussion in https://github.com/BHoM/BHoM/issues/537

#### Suggestions to restore compliance:
Change Fragments to be IObject instead of IBHoMObject.

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #563 

As agreed with @adecler, @al-fisher which asked me to action this (also, see discussion in https://github.com/BHoM/BHoM/issues/537):
changed IBHoMFragment to inherit IObject instead of IBHoMObject.

This allows to implement "lighter" fragments in all cases where the BHoMObject properties are not needed.

### Changelog

- Changed IBHoMFragment to implement IObject instead of IBHoMObject.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
One thing to check before merging is if there are any toolkits using the fragments that have been relying on the fragments also implicitly giving the IBHoMObject implementation.

I would assume not, as if you do not also inherit from BHoMObject that would mean you would have to add CustomData, name, GetShallowClone etc in each of those classes, but would you be able to make a quick check @alelom ?

**Comment by FraserGreenroyd** [comment]
> One thing to check before merging is if there are any toolkits using the fragments that have been relying on the fragments also implicitly giving the IBHoMObject implementation.
> 
> I would assume not, as if you do not also inherit from BHoMObject that would mean you would have to add CustomData, name, GetShallowClone etc in each of those classes, but would you be able to make a quick check @alelom ?

I've done that check as part of my review @IsakNaslundBh as that was my concern for Environment Fragments - I have found there are no issues on any Environmental toolkits as a result of this PR, but there is a need to remove the `BHoMObject` inheritance from Environmental Fragments which @alelom is raising an issue for me to resolve after this PR is merged :smile:

**Comment by alelom** [comment]
Thanks both, perfect comment syncronisation 😄 

@FraserGreenroyd: thank you! Issue here https://github.com/BHoM/BHoM/issues/575
@IsakNaslundBh will do further checks

**Comment by alelom** [comment]
From what I could gather, 
> One thing to check before merging is if there are any toolkits using the fragments that have been relying on the fragments also implicitly giving the IBHoMObject implementation.
> 
> I would assume not, as if you do not also inherit from BHoMObject that would mean you would have to add CustomData, name, GetShallowClone etc in each of those classes, but would you be able to make a quick check @alelom ?

this is never the case.

https://github.com/search?p=3&q=IBHoMFragment+org%3ABHoM+org%3ABuroHappoldEngineering&type=Code

**Comment by alelom** [comment]
I had a go with the CodeAssistant and no issue in compiling with any repository.

**Comment by alelom** [comment]
@al-fisher this is good for merge now.

**Pull request merged**
