### PR TITLE
Spatial_oM: Migrating grids and levels to Spatial

### LINKED ISSUE #756: Geometry_oM: Review of IGeometry and BHoMObjects and applicability for Geometry namespace
As discussed previously opportunity to clarify rules for which objects should reside in the Geometry Namespace. Intention has been for these to be Geometry primitives only - but we have necessarily included objects such as `ShapeProfiles` and the` SettingOut` objects such as `Grid` and `Level` largely to manage dependencies.

Option to impose that _all_ objects in Geometry_oM can _only_ be `IGeometry`.
Any Geometrical BHoMObject should therefore be moved to another namespace. We have had trouble defining what that namespace might be in the past! So good to have a focused thought and planning around this.

However we do now have `Spatial `as a namespace coming from our work on formalising the Dimensional Analysis which could perform that purpose for some objects?

We currently do not have a `Spatial_oM` - but I wonder if that could be useful for effectively foundational (and therefore useful across multiples disciplines) Geometrical Entities (that are not geometry primitives).
Like the ShapeProfiles and the SettingOut objects.

Thoughts?
Capturing this issue here now - to get comments - but also suggest we complete the next level detail of our class, namespace and interface mapping/diagram to create a comprehensive picture (including interactions with disciplines Environment and Structure) to plan changes and implementation priorities

@IsakNaslundBh @pawelbaran @adecler @rwemay @kThorsager

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #756

Migrating the last outstanding BHoMObjects, Level and Grid, out of Geometry_oM to Spatial_oM. Going forward, this mean the Geomtery namespace can be fully reserved to _only_ deal with pure geometrical concepts.

### Changelog

- Migrate Grids from Geometry to Spatial_oM
- Migrate Level from Geometry to Spatial_oM
- Add versioning from architectural grids and levels to migrated Spatial versions

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check versioning

**Review by FraserGreenroyd — APPROVED** [review]
I have reviewed the files changed and they match the discussions held on the topic. The bot has confirmed installer and versioning are happy with these changes, so I am happy to see these changes be merged into `main` from my perspective.

**Comment by FraserGreenroyd** [comment]
Following discussion with @IsakNaslundBh it is agreed to neutralise the remaining checks across this work, as the core issue is covered by `installer` and `versioning`.

@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, code-compliance, copyright-compliance, documentation-compliance, project-compliance, serialisation, ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting neutral checks on: core, code-compliance, copyright-compliance, documentation-compliance, project-compliance, serialisation, ready-to-merge

**Pull request merged**
