### PR TITLE
Environment_oM: TranslucentShade panel type

### LINKED ISSUE #1334: Environment_oM: TranslucentShade panel type
#### Description:

Need to add TranslucentShade as a Panel type enum to support the modelling of non-opaque shading elements e.g. glass fins or textile sails.

Relates to IES_TK issue: [#182](https://github.com/BHoM/IES_Toolkit/issues/182)

### PR DESCRIPTION
**Pull request by robinflyman**
Closes #1334 

Added a TranslucentShade panel type.

### CODE REVIEW

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
No qualms with the code changes themselves, but there needs to be a suitable label for the change log, and the PR title needs to include the oM which is being changed.

**Review by jamesramsden-bh — APPROVED** [review]
Enum added correctly, LGTM

**Comment by jamesramsden-bh** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check installer
@BHoMBot check versioning
@BHoMBot check ready-to-merge

**Pull request merged**
