### PR TITLE
MEP_oM: Ensure materials implement correct interface

### LINKED ISSUE #1158: MEP_oM: DuctMaterial is not a BH.oM.Physical.Materials.Material
After investigating why `DuctSectionProperty` from version 3.3 is not deserialising, I found out that the `DuctSectionProperty` is expecting a `BH.oM.Physical.Materials.Material` for its `BH.oM.Physical.Materials.Material` property BUT `DuctMaterial` is not a `Material` itself:

image

It was possible in 3.3 so not sure what is going on here.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
~~Beginning to resolve~~ Fixes #1158

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by michaelhoehn — APPROVED** [review]
LGTM

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
