### PR TITLE
Physical_oM: Add MaterialTakeoff class

### LINKED ISSUE #1422: Physical_oM: Change to methods required for IElementM
Given support for this given in discussion as well as offline calls, turning this into issue to be implemented!

### Discussed in https://github.com/orgs/BHoM/discussions/1399

<div type='discussions-op-text'>

<sup>Originally posted by **IsakNaslundBh** June  9, 2022</sup>
The `IElementM` currently have two required methods, `MaterialComposition` and `SolidVolume`, as outlined in https://github.com/BHoM/documentation/wiki/IElement-required-extension-methods .

For a lot of cases though, the volume needs to be computed as part of evaluating the Material composition, to ensure the correct ratios are computed. This can therefore be wasteful, and make the computation harder than it would be so simple return a material takeoff, with `volume : Material` pairs.

Suggesting that the requirements on the `IElementM` are changed to be that you have to do one or both of the options below:

1. Current requirement. Implement SolidVolume and MaterialComposition
2. Implement a MaterialTakeoff method that returns a class as described above (similar to MaterialComposition, but with volumes instead of rations of total volume)

It would be trivial for the MatterEngine to go from one too the other by simple addition/division, and this way the developer could implement whichever of the two is making most sense for the particular object.

You could ofc also implement both on a particular object, as long as you ensure that the results fully overlap for all cases.

Happy to hear thoughts from the group.

@JosefTaylor @michaelhoehn @FraserGreenroyd @enarhi @al-fisher @peterjamesnugent </div>

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #1422 

Adds class for MaterialTakeoff. Class for storing a set of materials and the corresponding volumes of said materials.

### CODE REVIEW

**Review by pawelbaran — CHANGES_REQUESTED** [review]
Please note this is to large extent a duplicate of https://github.com/BHoM/Revit_Toolkit/blob/main/Revit_oM/Misc/RevitMaterialTakeOff.cs - shouldn't the existing class be migrated or replaced?

**Comment by IsakNaslundBh** [comment]
> Please note this is to large extent a duplicate of https://github.com/BHoM/Revit_Toolkit/blob/main/Revit_oM/Misc/RevitMaterialTakeOff.cs - shouldn't the existing class be migrated or replaced?

Happy to migrate and version the existing revit class into this new one, as long as it does not have massive repercussions meaning this PR turns into to big of an alignment exercise. If the latter is the case, we can raise an issue and get it handled in a later PR push (this milestone). Are you fine with that @pawelbaran ?

@michaelhoehn I think you have used the pre-existing class the most, maybe you can chip in to say if it can safely be replaced by this new class or not (minding the slight difference in class structure, effectively doing the same thing).

**Comment by pawelbaran** [comment]
Sounds good to me, as long as we do not leave both items living separate lives in long term 👍

**Comment by IsakNaslundBh** [comment]
> Sounds good to me, as long as we do not leave both items living separate lives in long term 👍

Realised that https://github.com/BHoM/Revit_Toolkit/blob/main/Revit_Engine/Query/MaterialTakeOff.cs is 100% interfering with the current strategy, so will have to make a tweak anyway. Will put do-not-merge tags on this until we have a Revit solution up.

Might require a bit more discussion before that is actioned though, but thanks for flagging this @pawelbaran as it actually turned out to be a problem that needs to be fixed now.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by alelom — APPROVED** [review]
Code change looks good. Adding do-not-merge until I finish reviewing/testing connected PRs.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core
@BHoMBot check serialisation

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
