### PR TITLE
Upgrade BHoM to .Net Standard 2.0

### LINKED ISSUE #1291: Upgrade to .Net Standard 2.0
Per [this discussion](https://github.com/BHoM/BHoM/discussions/1263) update the BHoM to .Net Standard 2.0.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #1291 

### Additional comments
This will need checking against an installer which will be made shortly, as further updates need to be made to all toolkits in the installer - BHoM_Engine is going up to .Net Standard 2.0, and adapter toolkits will be going up to .Net Framework 4.7.2 to be compatible per the table outlined [here](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support)

### CODE REVIEW

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

Compiles with structural adapters, and all tested with them. All looks fine

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation
@BHoMBot check null-handling
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core
@BHoMBot check code-compliance
@BHoMBot check documentation-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check project-compliance
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check ready-to-merge

**Pull request merged**
