### PR TITLE
Diffing_oM: reworked `Diff` class; added `ComparisonInclusion` and a `ComparisonConfig` base class

### LINKED ISSUE #1318: Diffing_oM: remove the `ComparisonFunctions` object in favour of a more intuitive mechanism
#### Description:

As raised by @pawelbaran, align to the change needed for https://github.com/BHoM/BHoM_Engine/issues/2651

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes https://github.com/BHoM/BHoM/issues/1308
Closes #1318 

**Note**: this replaces https://github.com/BHoM/BHoM/pull/1306 due to rebase conflicts.

#### Simplification of the `Diff` object
The new Diff object has a simplified structure for the `ModifiedPropertiesPerObject` property (no more `Dictionary<Dictionary<Tuple<object, object>>>`). 

#### 1) `ComparisonInclusion` object

Added a `ComparisonInclusion` object that stores the result of the method of the same name, which can be implemented in specific Toolkits. This latter is called automatically by Diffing/Hash methods to determine if/how to include certain property differences. See https://github.com/BHoM/BHoM_Engine/pull/2699.

#### 2) `ComparisonConfig` class
Created a `ComparisonConfig` abstract class to allow Toolkits to implement more specific configurations. A default ComparisonConfig implementation is provided too.

#### 3) Removal of the `ComparisonFunctions` class
This also removes the object `ComparisonFunctions` related to the previous temporary solution that used delegates to resolve the `PropertyToInclude` diffing feature. This has been replaced by the `ComparisonInclusion()` method invoked through a `TryRunExtesionsMethod()` call. See https://github.com/BHoM/BHoM_Engine/pull/2699.

#### 4) New `PropertyNumericTolerance` class and related ComparisonConfig additions
This class allows to set custom tolerances per specific property names in the `ComparisonConfig`. 

#### Conclusion
This set of PRs is the final wave of big changes done to the Diffing and related objects/functions (e.g. Hash) in this Beta, and I expect that it will more or less settle here.
Once these are approved (i.e. we like the solution), I will document the entire structure of the code, add a proper wiki, diagrams and many tutorial resources.

### Test files

See https://github.com/BHoM/BHoM_Engine/pull/2699

### Changelog

- Added a `ComparisonInclusion` object that stores the result of the method of the same name, which can be implemented in specific Toolkits. This latter is called automatically by Diffing/Hash methods to determine if/how to include certain property differences. See https://github.com/BHoM/BHoM_Engine/pull/2699
- Created a `ComparisonConfig` abstract class to allow Toolkits to implement more specific configurations. A default ComparisonConfig implementation is provided too.
- Removed the previous solution that used ComparisonFunctions delegates.
- Added `ComparisonConfig` settings related to Numeric Tolerance and Significant Figures.

### CODE REVIEW

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check null-handling

**Review by pawelbaran — APPROVED** [review]

**Comment by alelom** [comment]
@BHoMBot check required

**Review by pawelbaran — APPROVED** [review]

**Comment by alelom** [comment]
Again risk of rebase failure (https://github.com/BHoM/BHoM/pull/1329/commits/cb7593375762cf03367cdb66c88699e6a4a9cf7e), closing and reopening

**Pull request closed without merging**
