### PR TITLE
Graphics_oM: Fix versioning file

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
Fixes the versioning file added in #1520

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a DevOps instruction. I am requesting force checks on: versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check copyright-compliance

**Review by IsakNaslundBh — APPROVED** [review]
Removals make sense.

Happy to approve now that versioning is passing

**Pull request merged**
