### PR TITLE
Physical_oM: Removes all checks from the constructor of the MaterialComposition

### LINKED ISSUE #1340: Physical_oM: Remove checks from MaterialComposition constructor
#### Broken rules:

Constructors for immutable objects should just assign properties. No checks should be made here, but all checks handled by create method(s).

#### Suggestions to restore compliance:

Remove checks done in constructor of `MaterialComposition` and just assign properties.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #1340

Removing checks from constructor and moving to Create method. A constructor should be a simple property assigner, not do additional checks.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
Will follow up with engine PR adding missing checks in the create method after the Reflection_oM/Engine changes have been done.

**Comment by IsakNaslundBh** [comment]
This should now be good to go!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Review by FraserGreenroyd — APPROVED** [review]
Have done a code review, this is sensible and in line with the issue and discussion, so am happy to see this merge to `main`.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Pull request merged**
