### PR TITLE
Create TestAdapterId.cs

### LINKED ISSUE #1636: Add TestAdapterId to be used for when required in automated UTs
#### Definition of the test :

For some datadriven UTs, there is a requirement to have an [AdapterId](https://github.com/BHoM/BHoM/blob/develop/BHoM/Interface/IAdapterId.cs) assigned to the incoming objects to be able to test the actual execution of the particular method.

Some tests have been set up with this in mind, using for example the [GSAId](https://github.com/BHoM/GSA_Toolkit/blob/develop/GSA_oM/Fragments/GSAId.cs). This causes issues with out automatic processes that only build what is required for the particular toolkit, rather building all toolkits. For example, when testing a method in the BHoM_Engine, the GSA_Toolkit will not, and should not, have been built. 

Suggesting to fix this is to add a new class in Test_oM implementing the IAdapterId, that the objects going in to UTs can use instead of the concrete ones from the toolkits.

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Closes #1636 

Adds a new TestAdapterId class to be used intead of conrete IAdapterIds for when required for UnitTests.

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by peterjamesnugent — APPROVED** [review]
Happy with the changes suggested - tested by creating a `TestAdapterId` and assigning it as a `Fragment` to a `BHoMObject`.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check core
@BHoMBot check serialisation
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
