### PR TITLE
Facade_oM: Added Results and Fragments for UValues Applied to Frames and Openings

### LINKED ISSUE #1250: Facade_oM: Results added for facade thermal analysis results
#### Description:
Addition of results objects to allow application of thermal analysis results to Facade objects.

### PR DESCRIPTION
**Pull request by enarhi**
### Issues addressed by this PR

Closes #1250 

This covers new additions of Psi and U value fragments applied to elements representing their thermal performance, and an Overall U Factor result that provides effective U Factor for one or more elements collectively.

### Test files
Test file included in the corresponding BHoM_Engine pr at https://github.com/BHoM/BHoM_Engine/pull/2515

### CODE REVIEW

**Review by vgreen-BH — DISMISSED** [review]
Reviewed with new U-value calc methods. LGTM

**Comment by enarhi** [comment]
@BHoMBot check required

**Comment by enarhi** [comment]
@BHoMBot check null-handling

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check compliance

**Comment by enarhi** [comment]
@BHoMBot check core

**Comment by enarhi** [comment]
@BHoMBot check versioning
@BHoMBot check serialisation

**Comment by enarhi** [comment]
@FraserGreenroyd regarding null-handling I have confirmed the increases in errors in unrelated to this branch and results from later merged pr's that reduce null handling errors.

**Review by vgreen-BH — APPROVED** [review]
lgtm

**Comment by enarhi** [comment]
@BHoMBot check installer

**Comment by enarhi** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
