### PR TITLE
Humans_oM: Refactor to c value objects

### LINKED ISSUE #951: Humans_oM: Add single point analysis option in CvalueFocalMethodEnum
#### Description:
https://github.com/BHoM/BHoM_Engine/issues/1904 suggests adding c-value calculation based on a single fixed point.
Will require small change in Humans_oM to include this method in the CvalueFocalMethodEnum.

### PR DESCRIPTION
**Pull request by rolyhudson**
### Issues addressed by this PR

Closes 
#951 
https://github.com/BHoM/BHoM/issues/1073
https://github.com/BHoM/BHoM_Engine/issues/2137

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by rolyhudson** [comment]
@BHoMBot check installer

**Comment by rolyhudson** [comment]
@BHoMBot check installer

**Review by al-fisher — APPROVED** [review]
LGTM @rolyhudson based on reviews provided here https://github.com/BHoM/BHoM_Engine/pull/2334 also

**Comment by al-fisher** [comment]
@BHoMBot check all

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]
Please resolve the versioning issues or raise an issue to have them resolved next week as a priority compliance fix in the final sprint :smile:

**Comment by FraserGreenroyd** [comment]
@BHoMBot check serialisation

**Comment by rolyhudson** [comment]
Created issue requesting versioning to be handle next week. https://github.com/BHoM/BHoM/issues/1221

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 2090603869

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check core

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
