### PR TITLE
BHoM: Move UnderlyingType to a sub folder

### LINKED ISSUE #1346: BHoM: Underlying type to be moved to a sub folder
This class does not make full sense to me in the basefolder next to the BHoMObejct. Would suggest moving it to a subfolder and potentially sub-namespace. `System` as a suggestion, but not sure that is ideal. Open for other ideas.

_Originally posted by @IsakNaslundBh in https://github.com/BHoM/BHoM/pull/1339#discussion_r782009398_

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #1346

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check versioning

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by IsakNaslundBh — APPROVED** [review]
Have compiled all PRs and tested opening a few scripts in Grasshopper and Excel - all working as expected. Happy to approve.

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
