### PR TITLE
BHoM: Fix root namespaces for Diffing and Facade oMs

### LINKED ISSUE #1269: Several assemblies have root namespaces suffixed *_oM
#### Broken rules:
The following assemblies have a root namespace ending `*_oM:`

- Diffing
- Facade

This is redundant information and inconsistent with the other assemblies in the BHoM solution.

#### Suggestions to restore compliance:
Remove the `*_oM` suffix - this may/will be a breaking change for anyone using the objects though good to tidy up while still in beta.

### PR DESCRIPTION
**Pull request by FraserGreenroyd**
### Issues addressed by this PR
Fixes #1269

### CODE REVIEW

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Review by enarhi — APPROVED** [review]
LGTM

**Review by IsakNaslundBh — APPROVED** [review]
LGTM!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
