### PR TITLE
Graphics_oM: Refactor `Vertex` and rename it to `RenderPoint`

### LINKED ISSUE #1273: Graphics_oM: Vertex doesn't follow naming conventions
#### Broken rules:

- The colour property is called `Color` (in AmE instead of BrE)
- If we go for https://github.com/BHoM/BHoM/issues/1271, then the object should be renamed to RenderPoint
- If we do both above, we allow the Vertex class to inherit from a [`IColourable` interface](https://github.com/BHoM/BHoM/issues/1272) common to the rest of "Render" objects

#### Suggestions to restore compliance:

- Rename `Vertex` to `RenderPoint` or `RenderVertex`
- Rename its `Color` property to `Colour`
- Make it implement [`IColourable` interface](https://github.com/BHoM/BHoM/issues/1272)

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #1273

### CODE REVIEW

**Review by enarhi — DISMISSED** [review]
LGTM assuming addition in Engine as noted by @al-fisher , tested per BHoM/Revit_Toolkit#1075 and behavior was as expected as well.

**Comment by alelom** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
