### PR TITLE
Geometry_oM: TaperedProfile added

### LINKED ISSUE #597: Geometry_oM: Add TaperedProfile
#### Description:

A number of BHoM support software uses tapered sections and I don't think it would be too hard to implement.

A `TaperedSteelSection` would own two `SteelSection` objects, i.e. `SteelSectionStart` and `SteelSectionEnd` (or we could go the i/j naming convention). 

The constructor would take a `Fabrication`, `PlateRestraint `and `Material `input and override those stored in the `SteelSection `objects. This is to prevent having a `SteelSectionStart `with a different Material to the `SteelSectionEnd`. 

We could write an Engine method to produce average `SectionProperties `for the `SectionProfile`, so that a `TaperedSteelSection `can be used with Toolkits that do not support tapering - this would required a warning message.

@IsakNaslundBh @rwemay @JosefTaylor @alelom thoughts?

### PR DESCRIPTION
**Pull request by peterjamesnugent**
### Issues addressed by this PR

Closes #597 

Added `TaperedProfile` class

### Test files

https://burohappold.sharepoint.com/:f:/s/BHoM/EpWxsmhBfgpCtXR4g3V6MbYBMghI4q9IwNsDOZ3xYlxbHg?e=Enzopz

### Changelog

Added `TaperedProfile` class

### CODE REVIEW

**Comment by peterjamesnugent** [comment]
Can this be reviewed soon (to allow time for changes), I am on leave tomorrow afternoon until Tuesday, so I will not be available for the sprint closure.

**Comment by IsakNaslundBh** [comment]
Parking this to 3.1. No Real point forcing this through without any support method for it in the engine and no support in the adapters. Lets get it in early in 3.1.

**Pull request merged**
