### PR TITLE
Base_oM: add a `UseGeometryHash` option to the `BaseComparisonConfig`

### LINKED ISSUE #1587: Base_oM: add a `UseGeometryHash` option to the BaseComparisonConfig to leverage it
#### Description:

Add a new `UseGeometryHash` option to the BaseComparisonConfig to leverage the new mechanism targeted by https://github.com/BHoM/BHoM_Engine/issues/3251

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #1587 

### Test files

See https://github.com/BHoM/BHoM_Engine/pull/3268

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Review by pawelbaran — APPROVED** [review]
Happy to approve following code review, testing and offline discussions with @alelom. Good stuff, thanks!

**Comment by alelom** [comment]
@BHoMBot check required

**Comment by alelom** [comment]
@BHoMBot check installer
@BHoMBot check versioning
@BHoMBot check ready-to-merge

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
