### PR TITLE
Analytical_oM: Refresh of Result interfaces

### PR DESCRIPTION
**Pull request by IsakNaslundBh**
### Issues addressed by this PR

Related to #1304

### CODE REVIEW

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer

**Comment by IsakNaslundBh** [comment]
@BHoMBot check installer
@BHoMBot check serialisation
@BHoMBot check versioning

**Comment by IsakNaslundBh** [comment]
Think this is ready to go now @alelom for first batch of simplification in support of #1304 .

I also fixed the structural results so they should be ready for potential future removal of the IAnalysisResult if we decide to to that later on.

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Comment by IsakNaslundBh** [comment]
@BHoMBot check compliance

**Review by alelom — APPROVED** [review]
Works well and decouples effectively! LGTM!

**Comment by IsakNaslundBh** [comment]
@BHoMBot check required

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
