### PR TITLE
LifeCycleAssessment_oM: Make GWP Results settable

### LINKED ISSUE #1163: LifeCycleAssessment_oM: Make GWP results settable
#### Description:

LCA engine requires modification of this property to allow for continuous calculations.

### PR DESCRIPTION
**Pull request by michaelhoehn**
### Issues addressed by this PR

Closes #1163 

### Test files

[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/LifeCycleAssessment_Toolkit/%23188-MultiQT.gh?csf=1&web=1&e=JSuSxF)

### CODE REVIEW

**Comment by michaelhoehn** [comment]
@BHoMBot check Installer

**Comment by michaelhoehn** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot this is a CI/CD instruction. I am authorising dispensation to be granted on check ref. 1738112867

**Pull request merged**
