### PR TITLE
Verification_oM: Code compliance fixed

### LINKED ISSUE #1650: Verification_oM: fix code compliance
#### Description:

Explicit interface implementation required on classes failing [here](https://github.com/BHoM/BHoM/pull/1649/checks?check_run_id=34181738447)

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #1650

### CODE REVIEW

**Comment by pawelbaran** [comment]
@BHoMBot check compliance

**Comment by pawelbaran** [comment]
@BHoMBot check required

**Review by IsakNaslundBh — APPROVED** [review]
Reviewed from a code perspective, and all changes makes sense. Happy to approve

**Comment by IsakNaslundBh** [comment]
@BHoMBot check ready-to-merge

**Pull request merged**
